---
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      APP_PORT: 8080
      APP_URL: http://localhost:8080
      APP_DEBUG_MODE: "true"
      DB_DRIVER: postgres
      DB_HOST: localhost
      DB_PORT: 2345
      DB_PASS: test_password
      DB_USERNAME: test_user
      DB_NAME: test_db
    depends_on:
      - migrations
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - 2345:5432

  migrations:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/test_db -user=test_user -password=test_password -connectRetries=60 migrate
    volumes:
      - ./flyway/migrations:/flyway/sql
    depends_on:
      - postgres
